### ISSUE TITLE
[A17] Better Workbench Management 

### ISSUE THREAD

**Issue by Danomano** [Falconne/ImprovedWorkbenches#16]
The link from the forums says that this is A17, however it doesn't work in A17. The mod wants the game to be updated to A18. Do you have a copy of the A17 Better Workbench Management mod that you can upload?

**Comment by Falconne** [comment]
Hmm, the link from the forum should go to https://github.com/Falconne/ImprovedWorkbenches/releases/tag/v17.10, which was the last release on A17. That package is not a rebuild, it's the same package that was being used on A17 before the update to B18.

Did you downgrade your HugsLib? That auto updates to the latest version and it's a dependency of this mod, so that might be what's producing the message.

**Comment by Falconne** [comment]
Hopefully this is no longer an issue?
